//

import Foundation

public protocol MergeRequestReportCaptionProviding {
    func reportCaption(commitSHA: String) -> String
}

public class MergeRequestReportCaptionProvider: MergeRequestReportCaptionProviding {
    private let dateFormatter: DateFormatter
    private let ciToolName: String

    public init(dateFormatter: DateFormatter, ciToolName: String) {
        self.dateFormatter = dateFormatter
        self.ciToolName = ciToolName
    }

    public convenience init(ciToolName: String) {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "EN_us")
        formatter.dateFormat = "HH:mm:ss.SSS zzz"
        self.init(dateFormatter: formatter, ciToolName: ciToolName)
    }

    public func reportCaption(commitSHA: String) -> String {
        """
        <p align="right">
        Generated by 🦾🤖
        \(ciToolName)
        against \(commitSHA)
        at \(dateFormatter.string(from: Date()))
        </p>
        """
    }
}
